[pytest]
DJANGO_SETTINGS_MODULE = tournament_platform.test_settings
python_files = test_*.py
python_classes = *Test
python_functions = test_*
testpaths = tests
pythonpath = app
addopts = --ignore=tests/test_integration_pg.py --ignore=tests/test_sql_queries.py
