# Generated by Django 6.0.5 on 2026-05-19 17:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_a', models.IntegerField(default=0)),
                ('score_b', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('scheduled', 'scheduled'), ('ongoing', 'ongoing'), ('finished', 'finished')], default='scheduled', max_length=10)),
                ('played_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'matches',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('organizer', 'organizer'), ('player', 'player')], default='player', max_length=20)),
                ('elo', models.IntegerField(default=1000)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='EloHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo_before', models.IntegerField()),
                ('elo_after', models.IntegerField()),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(db_column='match_id', on_delete=django.db.models.deletion.CASCADE, to='core.match')),
            ],
            options={
                'db_table': 'elo_history',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.PROTECT, related_name='owned_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(db_column='team_a_id', on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_a', to='core.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(db_column='team_b_id', on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_b', to='core.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner_team',
            field=models.ForeignKey(blank=True, db_column='winner_team_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='won_matches', to='core.team'),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('team', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, to='core.team')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'team_members',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('open', 'open'), ('ongoing', 'ongoing'), ('finished', 'finished')], default='draft', max_length=10)),
                ('format', models.CharField(choices=[('single_elimination', 'single_elimination'), ('round_robin', 'round_robin')], max_length=20)),
                ('max_teams', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_by', models.ForeignKey(db_column='created_by_id', on_delete=django.db.models.deletion.PROTECT, related_name='created_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tournaments',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(db_column='tournament_id', on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.tournament'),
        ),
        migrations.CreateModel(
            name='TournamentTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('team', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, to='core.team')),
                ('tournament', models.ForeignKey(db_column='tournament_id', on_delete=django.db.models.deletion.CASCADE, to='core.tournament')),
            ],
            options={
                'db_table': 'tournament_teams',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-elo'], name='users_elo_desc_idx'),
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('user', 'team'), name='team_members_pk'),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'open', 'ongoing', 'finished'])), name='tournaments_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(condition=models.Q(('format__in', ['single_elimination', 'round_robin'])), name='tournaments_format_valid'),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(condition=models.Q(('max_teams__gt', 0)), name='tournaments_max_teams_positive'),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='tournaments_end_date_gte_start_date'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament'], name='matches_tournament_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['played_at'], name='matches_played_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='tournamentteam',
            constraint=models.UniqueConstraint(fields=('tournament', 'team'), name='tournament_teams_pk'),
        ),
    ]
