# Generated by Django 6.0.5 on 2026-05-26 09:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='elo',
            field=models.IntegerField(db_index=True, default=1000),
        ),
        migrations.CreateModel(
            name='EloHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo_before', models.IntegerField()),
                ('elo_after', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('match', models.ForeignKey(db_column='match_id', on_delete=django.db.models.deletion.CASCADE, related_name='team_elo_history', to='tournaments.match')),
                ('team', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, related_name='elo_history', to='teams.team')),
            ],
            options={
                'db_table': 'team_elo_history',
                'indexes': [models.Index(fields=['team'], name='team_elo_history_team_idx'), models.Index(fields=['match'], name='team_elo_history_match_idx')],
                'constraints': [models.UniqueConstraint(fields=('team', 'match'), name='team_elo_history_unique_team_match')],
            },
        ),
    ]
